config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords:     'users/passwords',
  }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end

  resources :articles, only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
  end
  # searchwordを保存するアクションのURL
  get "articles/:id/save" => "articles#save_word"

  resources :users, only: [:show] do
    resources :browsing_histories, only: [:index]
    resources :searchwords, only: [:index, :create, :destroy]
  end
  get 'users/:id/quiz' => 'users#quiz', as: 'user_quiz'
  resources :genres, only: [:create]
  get "techcrunch" => "articles#techcrunch", as: "techcrunch"
  get "users/:id/favorites" => "users#favo_article", as: "favo_articles"
end

app/models/favorite.rb
# == Schema Information
#
# Table name: favorites
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  article_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_favorites_on_article_id  (article_id)
#  index_favorites_on_user_id     (user_id)
#

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    favorite = current_user.favorites.new(article_id: @article.id)
    favorite.save
    render 'favorite'
  end

  def destroy
    @article       = Article.find(params[:article_id])
    favorite = current_user.favorites.find_by(article_id: @article.id)
    favorite.destroy
    render 'favorite'
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if article.favorited_by?(current_user) %>
    <%= link_to article_favorites_path(article), method: :delete, remote: true do %>
        <i class="fa fa-thumbs-up" style="color: orange;" aria-hidden="true"></i>
        <%= article.favorites.count %>
    <% end %>
<% else %>
    <%= link_to article_favorites_path(article), method: :post, remote: true do %>
        <i class="fa fa-thumbs-up" aria-hidden="true"></i>
        <%= article.favorites.count %>
    <% end %>
<% end %>

app/views/favorites/favorite.js.erb
$('#favorite').html("<%= escape_javascript(render partial: 'favorites/favorite', locals: { article: @article}) %>");