config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords:     'users/passwords',
  }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end

  resources :articles, only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
  end
  # searchwordを保存するアクションのURL
  get "articles/:id/save" => "articles#save_word"

  resources :users, only: [:show] do
    resources :browsing_histories, only: [:index]
    resources :searchwords, only: [:index, :create, :destroy]
  end
  get 'users/:id/quiz' => 'users#quiz', as: 'user_quiz'
  resources :genres, only: [:create]
  get "techcrunch" => "articles#techcrunch", as: "techcrunch"
  get "users/:id/favorites" => "users#favo_article", as: "favo_articles"
end

app/models/searchword.rb
# == Schema Information
#
# Table name: searchwords
#
#  id           :integer          not null, primary key
#  word_name    :string
#  word_meaning :string
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_searchwords_on_user_id  (user_id)
#

class Searchword < ApplicationRecord
  belongs_to :user
end

app/controllers/searchwords_controller.rb
class SearchwordsController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def index
    @words = current_user.searchwords.order(created_at: :desc).all
  end

  def create
  end

  def destroy
    @word = current_user.searchwords.find(params[:id])
    @word.destroy
    redirect_to user_searchwords_path
  end
end

app/helpers/searchwords_helper.rb
module SearchwordsHelper
end

app/views/searchwords/destroy.js.erb
$('#searchword-<%= @word.id %>').html('');

app/views/searchwords/index.html.erb
<h1 class="seachword-title">Search Words</h1>
<% if @words.present? %>
    <table class="table">
        <thead>
                <tr class="table-header">
                    <th>English</th>
                    <th>Japanese</th>
                    <th></th>
                </tr>
        </thead>
        <tbody>
            <% @words.each do |word| %>
                <tr class="active" id="search-#{word.id}">
                    <td><%= word.word_name %></td>
                    <td><%= word.word_meaning %></td>
                    <td>
                        <%= link_to user_searchword_path(current_user.id, word.id), method: :delete, remote: true do %>
                            <i class="btn btn-warning">✖</i>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <h2 style="margin-left: 100px;">検索ワードがありません</h2>
<% end %>