config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords:     'users/passwords',
  }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end

  resources :articles, only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
  end
  # searchwordを保存するアクションのURL
  get "articles/:id/save" => "articles#save_word"

  resources :users, only: [:show] do
    resources :browsing_histories, only: [:index]
    resources :searchwords, only: [:index, :create, :destroy]
  end
  get 'users/:id/quiz' => 'users#quiz', as: 'user_quiz'
  resources :genres, only: [:create]
  get "techcrunch" => "articles#techcrunch", as: "techcrunch"
  get "users/:id/favorites" => "users#favo_article", as: "favo_articles"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  name                   :string
#  profile_image          :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :searchwords
  has_many :favorites, dependent: :destroy
  has_many :browsing_histories, dependent: :destroy
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_up_path_for(resource)
    articles_path
  end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    def index
    end

    def show
        @user = User.find(params[:id])
    end

    def favo_article
        @favos = current_user.favorites.all
    end

    def quiz
    #     words = current_user.searchwords.where(user_id: current_user.id)
    #     @selects  = []
    #     words.each do |w|
    #         selects << {quiz: w, }
        # array = []
        # words = Searchword.pluck(user_id: current_user.id, :)
        # array << words
        # @hoge = array
        @search = Searchword.where(user_id: current_user.id)
        if @search.present?
            words = @search.pluck(:word_name, :word_meaning)
            word = words.sample
            array = []
            array << word
            @q = array[0][0]
            @a = array[0][1]
            gon.correct_answer = array[0][1]
        end
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_favo_articles.html.erb
<% @favos.each do |favo| %>
    <li class="article clearfix">
        <%= link_to article_path(favo.article.id) do %>
            <% if favo.article.article_image %>
                <div class="article-left"><img src=<%= favo.article.article_image %>></div>
            <% end %>
                <ul class="article-right">
                <li class="article-title"><%= truncate(favo.article.title, length: 50) %></li>
                <li class="iine-count">👍<%= favo.article.favorites.count %></li>
            </ul>
        <% end %><br>
    </li>
<% end %>

app/views/users/favo_article.html.erb
<div class="container">
    <div class="row">
        <div id="news col-xs-offset-2 col-xs-8">
            <h1>お気に入り記事</h1>
            <ul>
                <div id="favo_article_lists">
                    <% if @favos.present? %>
                        <strong><%= render 'users/favo_articles' %></strong>
                    <% else %>
                        <h2>お気に入り記事がありません</h2>
                    <% end %>
                </div>
            </ul>
        </div>
    </div>
</div>

app/views/users/favo_articles.js.erb
$('#favo_article_lists').append("<%= escape_javascript(render partial: 'users/favo_articles', favos: @favos) %>");

app/views/users/quiz.html.erb
<div class="container">
    <div class="row">
        <div class="quiz">
            <div class="quiz-title">
                <h1>単語クイズ</h2>
            </div>
            <% if @search.present? %>
                <p class="question">問題： <%= @q %></p>
                <input type="hidden" name="hidden" class="correct" val=<%= @a %>>
                <form name="answerform">
                <input type="text" class="answer_form"><br>
                <button type="button" class="check">答え合わせ</button><br>

                <div class="announce"></div>
                <div class="youranswer"></div>
                <div class="aaa"></div>
                <div class="next-quiz">
                    <%= link_to user_quiz_path(current_user.id) do %>
                        <button>次の問題</button>
                    <% end %>
                </div>
            <% else %>
                <h2>検索ワードがありません</h2>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<ul>
    <div class="upper-btn">
        <li><%= link_to favo_articles_path(current_user.id) do %><div class="select btn btn-secondary col-12"><p>FaVo Articles</p></div><% end %></li>
        <li><%= link_to user_searchwords_path(current_user.id) do %><div class="select btn btn-secondary col-12"><p>SearcHed WOrds</p></div><% end %></li>
    </div>
    <div class="down-btn">
        <li><%= link_to user_browsing_histories_path(current_user.id) do %><div class="select btn btn-secondary col-12"><p>BrowsEd ArTicleS</p></div><% end %></li>
        <li><%= link_to user_quiz_path(current_user.id) do %><div class="select btn btn-secondary col-12"><p>Quiz!!</p></div><% end %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %><div class="select btn btn-secondary col-12"><p>Log Out</p></div><% end %></li>
    </div>
</ul>