config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords:     'users/passwords',
  }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end

  resources :articles, only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
  end
  # searchwordを保存するアクションのURL
  get "articles/:id/save" => "articles#save_word"

  resources :users, only: [:show] do
    resources :browsing_histories, only: [:index]
    resources :searchwords, only: [:index, :create, :destroy]
  end
  get 'users/:id/quiz' => 'users#quiz', as: 'user_quiz'
  resources :genres, only: [:create]
  get "techcrunch" => "articles#techcrunch", as: "techcrunch"
  get "users/:id/favorites" => "users#favo_article", as: "favo_articles"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tnews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon(init: true) %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="header-container">
        <div class="header-title text-center">
          <%= link_to articles_path do %>
            <p><strong>Tnews</strong></p>
          <% end %>
        </div>
      </div>
    </div>
    <%= yield %>
    <% if user_signed_in? %>
      <div class="footer">
        <ul class="footer_menu">
          <li><%= link_to user_path(current_user.id) do %><strong class="fa fa-home"></strong><% end %></li>
          <li><%= link_to articles_path do %><strong class="fa fa-bars"></strong><% end %></li>
          <li><%= link_to techcrunch_path do %><strong class="fa fa-laptop"></strong><% end %></li>
        </ul>
      </div>
    <% end %>
  </body>
</html>